* @tf.function (way to speed up regular pyhton funcitons)


#Introduction to Tensors
* tf.constant

In [1]:
# Import tensor flow 
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
# Create a scalar
# ctrl+sfhit+space for explanation of a code (click on it first)
scalar = tf.constant(7)
print(scalar)
scalar

tf.Tensor(7, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimension (ndim)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix 1
matrix_1 = tf.constant([[10, 7],
                        [7, 10]])
matrix_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix_1.ndim

2

In [ ]:
# Create a matrix 2
matrix_2 = tf.constant([[10., 7.],
                        [3., 2.],
                        [8., 9.]], dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
matrix_2.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       
                      [[7, 8, 9],
                       [10, 11, 12]],
                       
                      [[13, 14, 15],
                       [16, 17, 18]],
                      
                      [[19, 20, 21],
                       [22, 23, 24]]])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## Summary
* Scalar: single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimension array of numbers
* Tensor: an n-dimensional array of numbers

**ndim = total number of elements in a shape of tensor**

# Create tensors with tf.Variable
* compare variable vs constant


In [ ]:
# tf.Variable used when values are expected to change
# tf.constant used when values are not expected to change
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Changes the value at the index 0
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# tf.constant does not support assignment
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

# Create random tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
print(random_1, "\n")

random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

print(random_1, random_2, random_1 == random_2, sep="\n"*2)



tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)

tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


#Shuffle tensors

In [ ]:
tf.random.set_seed(25) # use global seed to get reproducible random numbers
not_shuffled = tf.constant([[10, 7],
                            [3, 2],
                            [1, 5]])
shuffled = tf.random.shuffle(not_shuffled, seed=100) # use operation level seed not to get reproducible numbers
not_shuffled, shuffled


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  2],
        [ 1,  5]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  2],
        [ 1,  5],
        [10,  7]], dtype=int32)>)

#Other ways to make tensors

In [ ]:
# create a tensor made of all ones
tf.ones([2, 2, 2], dtype=tf.int64)

<tf.Tensor: shape=(2, 2, 2), dtype=int64, numpy=
array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])>

In [ ]:
# create a tensor made of all zeros
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

#Turn NumPy arrays into tensors
difference is that Tensorflow tensors can be run on GPU = faster

In [ ]:
# create tensors from NumPy array
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32) # last number not included
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# turn numpy into tensorflow and also you can change the sape
A = tf.constant(numpy_A, shape=(2, 3, 4), dtype=tf.int32)
B = tf.constant(A, shape=24)
print(A, B, sep="\n"*2, end="\n")
# nupy arrays can be without commas

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)


#Get information from tensors
* shape - tensor.shape
* rank - tensor.ndim
* axis or dimension - tensor[0], tensor[:, 1], ...
* size - tf.size(tensor)

In [ ]:
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
print(
    "Datatype of every element:", rank_4_tensor.dtype,
    "Shape of a tensor:", rank_4_tensor.shape,
    "Number of dimensions (rank):", rank_4_tensor.ndim,
    "Elements along the 0 axis:", rank_4_tensor.shape[0],
    "Elements along the last axis:", rank_4_tensor.shape[-1],
    "size:", tf.size(rank_4_tensor).numpy(),
    sep="\n")
# by axis is meant position of dimension. rank_4_tensor.shape[0] will return 2 because it is the first dimension in shape of tensor
# 2:05:03

Datatype of every element:
<dtype: 'float32'>
Shape of a tensor:
(2, 3, 4, 5)
Number of dimensions (rank):
4
Elements along the 0 axis:
2
Elements along the last axis:
5
size:
120


# Indexing of tensors
tensors can be indexed just like lists in python

In [ ]:
# get first two elements of each dimension
#rank_4_tensor[:2, :2, :2, :2]
tensor_x = tf.constant(np.arange(0, 240, 1), shape=(4, 6, 10))
print(tensor_x[:, 0, :])
print(tensor_x)

tf.Tensor(
[[  0   1   2   3   4   5   6   7   8   9]
 [ 60  61  62  63  64  65  66  67  68  69]
 [120 121 122 123 124 125 126 127 128 129]
 [180 181 182 183 184 185 186 187 188 189]], shape=(4, 10), dtype=int64)
tf.Tensor(
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]]

 [[ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]

 [[120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 1

In [ ]:
# get the first index of each dimension from each index except the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# play around with slicing

rank_4_tensor[:1, :, :, :]
# colon in brackets means get everything
# tested and this slicing has similar logic as normal lists, but it seems that [:1, :, :, :] does not work on normal lists

<tf.Tensor: shape=(1, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# create rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([1, 2, 3, 4],shape=(2, 2))
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# add new dimension to a tensor, variant 1
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
print(rank_3_tensor)

# the three dots mean this:
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis] # :, :, means every axis before the last one
print(rank_3_tensor)

rank_3_tensor = rank_2_tensor[tf.newaxis, ...]
print(rank_3_tensor)

rank_3_tensor = rank_2_tensor[:, tf.newaxis, :]
print(rank_3_tensor)



tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)
tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]], shape=(1, 2, 2), dtype=int32)
tf.Tensor(
[[[1 2]]

 [[3 4]]], shape=(2, 1, 2), dtype=int32)


In [ ]:
# add new dimension to a tensor, variant 2
tf.expand_dims(rank_2_tensor, -1) # expand axis on the last index

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

# Manipulating tensors (tensor operations)
**basic operations**
+, -, *, /



In [ ]:
# you can change values of a tensor using operator signs
tensor_a = tf.constant([[2, 4],
                       [6, 8]],
                       dtype=tf.float64)
tensor_a * 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[20., 40.],
       [60., 80.]])>

In [ ]:
tensor_a / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [ ]:
# original tensor is unchanged
tensor_a

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2., 4.],
       [6., 8.]])>

In [ ]:
# we can use tf functions to change the tensor values, example

tf.multiply(tensor_a, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[20., 40.],
       [60., 80.]])>

**matrix multiplication (aka "dot product")**
* one of the most common ml operations

Rules:
1. the inner dimensions must match = tensor1-shape(2, 3) tesnor2-shape(3, 1)
  the inner dims match here (nr 3), it will work
2. the output shape has the same dimension as the outer dims = (2, 1)

In [ ]:
# use tf.linalg.matmul() -- the middle part can be usually skipped in tf (linalg), tested it and sometimes the middle part has to be included
tf.matmul(tensor_a, [[2, 2], [4, 4]])

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[20., 20.],
       [44., 44.]])>

In [ ]:
# Python operator for matrix multiplication
tensor_a @ [[2, 2], [4, 4]]

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[20., 20.],
       [44., 44.]])>

In [ ]:
# another operator for matrix multiplication with specified axis, which then changes the output shape
tf.tensordot(tensor_a, tensor_a, 1)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[28., 40.],
       [60., 88.]])>

In [ ]:
# difference between matrix multiplication and basic multiplication here:
# "multiply" multiplies only across the same dimensions or items lets say 
tf.multiply(tensor_a, [[2, 2], [4, 4]])

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 4.,  8.],
       [24., 32.]])>

In [ ]:
# try to multiply matrices with the same shape, but it will not work. Therefore later have to reshape
tensor_b = tf.ones(shape=(3,2))
tensor_c = tf.ones(shape=(3, 2))
print(tensor_b)
# print(tf.matmul(tensor_b,tensor_c)) # this will not work because tensors have not the same shape

tensor_d = tf.reshape(tensor_c, (2, 3))
print(tensor_d)
print(tf.matmul(tensor_b, tensor_d))


tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]], shape=(3, 3), dtype=float32)


In [ ]:
# try to reshape the first matrix instead of the second one
tf.matmul(tf.reshape(tensor_b,(2, 3)), tensor_c)

# the result is different compared to when the later matrix was reshaped. It makes sense, but nevertheless keep it in mind.

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>

In [ ]:
# difference between tf.transpose and tf.reshape
tensor_e = tf.constant([[1, 2],
                        [3, 4],
                        [5, 6]])
print(
    "original:", tensor_e,
    "transpose:", tf.transpose(tensor_e),
    "reshape:", tf.reshape(tensor_e, (2, 3)),
    sep="\n"
    )

original:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
transpose:
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
reshape:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# stack can put together arrays and flip them based on chosen axis (fyi AXIS = DIMENSION)
# TO DO: create tensor with different dimensions in some other file and check how it changes based on axis

x = tf.constant([[1, 2], [3, 4]])
y = tf.constant([[5, 6], [7, 8]])
z = tf.constant([[9, 10], [11, 12]])

axis_0 = tf.stack([x, y, z], axis=0)
axis_1 = tf.stack([x, y, z], axis=1)
axis_n1 = tf.stack([x, y, z], axis=-1)
axis_2 = tf.stack([x, y, z], axis=2)
axis_n2 = tf.stack([x, y, z], axis=-2)

print("Number of dimensions of x (original):", x.ndim)
print("Number of dimensions of x after stack of [x, y]:", tf.stack([x, y], axis=0).ndim)
print("Number of dimensions of x after stack of [x, y, z]:", tf.stack([x, y, z], axis=0).ndim)
print("axis 0", axis_0, sep="\n", end="\n"*2)
print("axis 1", axis_1, sep="\n", end="\n"*2)
print("axis -1", axis_n1, sep="\n", end="\n"*2)
print("axis 2", axis_2, sep="\n", end="\n"*2)
print("axis -2", axis_n2, sep="\n", end="\n"*2)

print("axis 1 == axis -2", axis_1 == axis_n2, sep="\n", end="\n"*2)
print("axis -1 == axis 2", axis_n1 == axis_2, sep="\n", end="\n"*2)

# Change a datatype of a tensor
* default is 32bit precision

In [ ]:
tensor_f = tf.constant([-2.5, -3.4])
tensor_f.dtype


tf.float32

In [ ]:
tensor_g = tf.constant([3, 4])
tensor_g.dtype

tf.int32

In [ ]:
# change the dtype aka datatype and check the precision
tensor_g_16bit = tf.cast(tensor_f, dtype=tf.float16)
tensor_g_16bit.dtype, tensor_g_16bit[1].numpy()

(tf.float16, -3.4)

In [ ]:
tensor_g_64bit = tf.cast(tensor_f, dtype=tf.float64)
tensor_g_64bit.dtype, tensor_g_64bit[1].numpy()

(tf.float64, -3.4000000953674316)

In [ ]:
tensor_g_128bit = np.array([-2.5, -3.4],dtype=np.float128)
tensor_g_128bit.dtype, tensor_g_128bit[1]

(dtype('float128'), -3.3999999999999999112)

# Aggregating tensors
aggregate means to compress bigger tensors to smaller

In [ ]:
# get the absolute values - tf.abs()
print(tf.constant([-1, -1]))
print(tf.abs(tf.constant([-1, -1])))
  

tf.Tensor([-1 -1], shape=(2,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)


Next examples:
* get the minimum of a tensor
* get the maximum of a tensor
* get the mean ...
* get the sum ...

In [ ]:
tensor_h = tf.constant(np.random.randint(0, 100, size=50), shape=(2, 5, 5), dtype=tf.float64)
print(tensor_h, end="\n"*2)


tf.Tensor(
[[[98. 60. 26. 17. 80.]
  [12. 87. 47. 90. 99.]
  [99. 66. 68. 31. 24.]
  [85. 44.  7. 35. 88.]
  [ 2. 60. 75. 47. 91.]]

 [[16. 80. 10. 84. 64.]
  [34. 61. 81. 77. 70.]
  [24. 31. 62. 82. 50.]
  [79. 78. 30. 41. 11.]
  [60. 69. 73. 51. 69.]]], shape=(2, 5, 5), dtype=float64)


In [ ]:
print(
    "max:", tf.reduce_max(tensor_h).numpy(),
    "min:", tf.reduce_min(tensor_h).numpy(),
    "mean:", tf.reduce_mean(tensor_h).numpy(),
    "sum:", tf.reduce_sum(tensor_h).numpy(),
    sep="\n"
    )

# np.min() is the equivalent to tf.reduce_min()
# 3:12:13

max:
99.0
min:
2.0
mean:
56.5
sum:
2825.0


In [ ]:
# variance and standart deviation
print(
    "variance:", tf.math.reduce_variance(tensor_h).numpy(),
    "standard deviation:", tf.math.reduce_std(tensor_h).numpy()
)

variance: 757.09 standard deviation: 27.51526848860465


# Find positional maximum and minimum
* explained in vid 3:26:00 +-


In [ ]:
# crate a tensor
tf.random.set_seed(100) # random numbers here will be the same for each other iteration
tensor_i = tf.random.uniform([50])
tensor_i

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.24900055, 0.48465526, 0.39165282, 0.8218267 , 0.23590696,
       0.39270067, 0.96157587, 0.7378106 , 0.3086977 , 0.7820475 ,
       0.36411405, 0.43852115, 0.39143312, 0.4100443 , 0.15650964,
       0.16554844, 0.11952579, 0.99199855, 0.07539165, 0.69944966,
       0.3041743 , 0.6850517 , 0.95208406, 0.65089023, 0.48965216,
       0.64302886, 0.50323474, 0.37081254, 0.50158453, 0.65716815,
       0.42388284, 0.6438379 , 0.7099544 , 0.8554728 , 0.10746086,
       0.1302582 , 0.74147284, 0.7842232 , 0.16333139, 0.18595266,
       0.47453701, 0.6588017 , 0.9707295 , 0.62733424, 0.40020967,
       0.9673735 , 0.13458717, 0.6554717 , 0.4056772 , 0.18046606],
      dtype=float32)>

In [ ]:
# find positional maximum - returns an index of a biggest number across axis 
tf.argmax(tensor_i).numpy(), np.argmax(tensor_i), tensor_i[np.argmax(tensor_i)].numpy()

(17, 17, 0.99199855)

In [ ]:
# find poistional minimum
tf.argmin(tensor_i).numpy(), tensor_i[np.argmin(tensor_i)].numpy()

(18, 0.07539165)

In [ ]:
# sort the indexes based on their values (this was only tested for fun)
argsort_ = tf.argsort(tensor_i, direction="DESCENDING")
print(argsort_)
print([tensor_i[x].numpy() for x in argsort_])


tf.Tensor(
[17 42 45  6 22 33  3 37  9 36  7 32 19 21 41 29 47 23 31 25 43 26 28 24
  1 40 11 30 13 48 44  5  2 12 27 10  8 20  0  4 39 49 15 38 14 46 35 16
 34 18], shape=(50,), dtype=int32)
[0.99199855, 0.9707295, 0.9673735, 0.96157587, 0.95208406, 0.8554728, 0.8218267, 0.7842232, 0.7820475, 0.74147284, 0.7378106, 0.7099544, 0.69944966, 0.6850517, 0.6588017, 0.65716815, 0.6554717, 0.65089023, 0.6438379, 0.64302886, 0.62733424, 0.50323474, 0.50158453, 0.48965216, 0.48465526, 0.47453701, 0.43852115, 0.42388284, 0.4100443, 0.4056772, 0.40020967, 0.39270067, 0.39165282, 0.39143312, 0.37081254, 0.36411405, 0.3086977, 0.3041743, 0.24900055, 0.23590696, 0.18595266, 0.18046606, 0.16554844, 0.16333139, 0.15650964, 0.13458717, 0.1302582, 0.11952579, 0.10746086, 0.07539165]


# Squeezing a tensor (removing all single dimensions)

In [ ]:
# create a tensor
tensor_j = tf.random.uniform([1, 1, 4, 20])
print(tensor_j , f"Number of dims: {tensor_j.ndim}", sep="\n"*2)
      


tf.Tensor(
[[[[0.76732683 0.17561221 0.7366072  0.7058151  0.42422843 0.06578231
    0.4311316  0.76413023 0.73609316 0.90818596 0.7354207  0.01241052
    0.15185893 0.14998662 0.69694173 0.8881475  0.10579085 0.08278334
    0.05811858 0.05356407]
   [0.46689498 0.7063756  0.03284144 0.44032717 0.40474534 0.08734787
    0.9362178  0.09859371 0.34985936 0.8211818  0.22784019 0.79620624
    0.6228684  0.45856822 0.09262025 0.58145595 0.54290843 0.5207161
    0.10830402 0.4017836 ]
   [0.035344   0.94818926 0.13332808 0.4160583  0.79990864 0.35621738
    0.8081254  0.18336403 0.7843964  0.5925404  0.16908884 0.4484626
    0.2532071  0.37594247 0.2506069  0.06518686 0.06556642 0.1422602
    0.26682842 0.34116328]
   [0.30482972 0.03387415 0.81038296 0.24236    0.09707737 0.7006737
    0.73452437 0.8195565  0.04001427 0.5229819  0.4626323  0.3398893
    0.6346036  0.28389263 0.3848456  0.9379796  0.32063222 0.29029357
    0.48852468 0.0631355 ]]]], shape=(1, 1, 4, 20), dtype=float32)

Numbe

In [ ]:
# remove the single dimensions

print(tf.squeeze(tensor_j) , f"Number of dims: {tf.squeeze(tensor_j).ndim}", sep="\n"*2)

tf.Tensor(
[[0.76732683 0.17561221 0.7366072  0.7058151  0.42422843 0.06578231
  0.4311316  0.76413023 0.73609316 0.90818596 0.7354207  0.01241052
  0.15185893 0.14998662 0.69694173 0.8881475  0.10579085 0.08278334
  0.05811858 0.05356407]
 [0.46689498 0.7063756  0.03284144 0.44032717 0.40474534 0.08734787
  0.9362178  0.09859371 0.34985936 0.8211818  0.22784019 0.79620624
  0.6228684  0.45856822 0.09262025 0.58145595 0.54290843 0.5207161
  0.10830402 0.4017836 ]
 [0.035344   0.94818926 0.13332808 0.4160583  0.79990864 0.35621738
  0.8081254  0.18336403 0.7843964  0.5925404  0.16908884 0.4484626
  0.2532071  0.37594247 0.2506069  0.06518686 0.06556642 0.1422602
  0.26682842 0.34116328]
 [0.30482972 0.03387415 0.81038296 0.24236    0.09707737 0.7006737
  0.73452437 0.8195565  0.04001427 0.5229819  0.4626323  0.3398893
  0.6346036  0.28389263 0.3848456  0.9379796  0.32063222 0.29029357
  0.48852468 0.0631355 ]], shape=(4, 20), dtype=float32)

Number of dims: 2


# One-hot enocoding tensors

In [ ]:
 # create a list of indices
 some_list = [0, 1, 2, 3] # could be red, green, blue, purple colors

 # one-hot enocde the list of indices
 tf.one_hot(some_list, 4).numpy()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [ ]:
# specifiy custom values for one-hot encoding (rarely used)
tf.one_hot(some_list, depth=4, on_value="True", off_value="X")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'True', b'X', b'X', b'X'],
       [b'X', b'True', b'X', b'X'],
       [b'X', b'X', b'True', b'X'],
       [b'X', b'X', b'X', b'True']], dtype=object)>

# Squaring, log, square root - another mathematical operations

In [ ]:
# create a tensor
tensor_k = tf.range(1, 10)
tensor_k

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# square it
tf.square(tensor_k)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# square root (have to use float, else error)
#tf.cast(tf.math.sqrt(tensor_k), dtype=tf.float32)

In [ ]:
# find the natural logarithm
#tf.cast(tf.math.log(tensor_k), tf.float32)

# Tensor flow and NumPy

In [ ]:
# create a tensor directly from numpy array
tensor_L = tf.constant(np.array([1., 5., 4., 13.,]))
tensor_L

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 1.,  5.,  4., 13.])>

In [ ]:
# convert back to numpy array
np.array(tensor_L), tensor_L.numpy(), type(np.array(tensor_L)), type(tensor_L.numpy())

(array([ 1.,  5.,  4., 13.]),
 array([ 1.,  5.,  4., 13.]),
 numpy.ndarray,
 numpy.ndarray)

In [ ]:
# get an index position
tensor_L.numpy()[3]

13.0

In [ ]:
# difference in default dtype
tensor_L_1 = tf.constant([1., 5.],)
numpy_L_1 = np.array([1., 5.,],)

print(tensor_L_1, numpy_L_1, tensor_L_1.dtype, numpy_L_1.dtype, sep="\n", end="\n\n")

tensor_L_2 = tf.constant([1., 5.],)
numpy_L_2 = tf.constant(np.array([1., 5.,],))

print(tensor_L_2, numpy_L_2, tensor_L_2.dtype, numpy_L_2.dtype, sep="\n")

tf.Tensor([1. 5.], shape=(2,), dtype=float32)
[1. 5.]
<dtype: 'float32'>
float64

tf.Tensor([1. 5.], shape=(2,), dtype=float32)
tf.Tensor([1. 5.], shape=(2,), dtype=float64)
<dtype: 'float32'>
<dtype: 'float64'>
